---
name: Build test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-make:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          os: [ "alpine", "archlinux", "fedora", "ubuntu" ]

    container:
      image: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          ./scripts/install-deps.sh

      - name: Build
        run: |
          SETUPTOOLS_SCM_PRETEND_VERSION="0" make

      - name: Run check
        run: |
          SETUPTOOLS_SCM_PRETEND_VERSION="0" make check
  build-meson:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          os: [ "alpine", "archlinux", "fedora", "ubuntu" ]

    container:
      image: ${{ matrix.os }}

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: "${GITHUB_WORKSPACE}/scripts/install-deps.sh"

      - name: Build
        run: |
          meson setup . _build
          meson compile -C _build
